-- ===============================
-- CLEANUP
-- ===============================
DROP TABLE IF EXISTS invoice_items CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS locations CASCADE;

-- ===============================
-- TABLES
-- ===============================

-- Clients
CREATE TABLE clients (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref CHAR(15) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone TEXT,
  address TEXT,
  pwd TEXT,
  observation TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Categories
CREATE TABLE categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref CHAR(15) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Products
CREATE TABLE products (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref CHAR(15) UNIQUE NOT NULL,
  category_id INT REFERENCES categories(id) ON DELETE SET NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price NUMERIC(12,2),
  qte INT,
  picture TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Invoices
CREATE TABLE invoices (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref CHAR(15) UNIQUE NOT NULL,
  client_id INT REFERENCES clients(id) ON DELETE SET NULL,
  total NUMERIC(12,2),
  status VARCHAR(50),
  client TEXT,
  observation TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Invoice Items
CREATE TABLE invoice_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id INT REFERENCES invoices(id) ON DELETE CASCADE,
  product_id INT REFERENCES products(id) ON DELETE SET NULL,
  qte INT,
  price NUMERIC(12,2),
  total NUMERIC(12,2),
  product TEXT,
  observation TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Locations
CREATE TABLE locations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  tracker_id TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  accuracy DOUBLE PRECISION,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===============================
-- DISABLE ROW LEVEL SECURITY
-- ===============================
ALTER TABLE clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE locations DISABLE ROW LEVEL SECURITY;

-- ===============================
-- INDEXES
-- ===============================
CREATE INDEX idx_invoices_client_id ON invoices (client_id);
CREATE INDEX idx_invoice_items_invoice_id ON invoice_items (invoice_id);
CREATE INDEX idx_invoice_items_product_id ON invoice_items (product_id);
CREATE INDEX idx_products_category_id ON products (category_id);

-- ===============================
-- TRIGGER FOR CREATED_AT / UPDATED_AT
-- ===============================
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.created_at := OLD.created_at; -- keep created_at
  NEW.updated_at := NOW();          -- update updated_at
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach triggers to all tables
CREATE TRIGGER trg_clients_updated
BEFORE UPDATE ON clients
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trg_categories_updated
BEFORE UPDATE ON categories
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trg_products_updated
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trg_invoices_updated
BEFORE UPDATE ON invoices
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trg_invoice_items_updated
BEFORE UPDATE ON invoice_items
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trg_locations_updated
BEFORE UPDATE ON locations
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

-- ===============================
-- TRIGGERS FOR AUTO-FILLING
-- ===============================

-- Fill invoice_items.product with product name if null/empty
CREATE OR REPLACE FUNCTION fill_invoice_item_product()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.product IS NULL OR LENGTH(TRIM(NEW.product)) = 0 THEN
    SELECT name INTO NEW.product
    FROM products
    WHERE id = NEW.product_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_invoice_items_fill_product
BEFORE INSERT OR UPDATE ON invoice_items
FOR EACH ROW EXECUTE FUNCTION fill_invoice_item_product();

-- Fill invoices.client with clients.name if null/empty
CREATE OR REPLACE FUNCTION fill_invoice_client()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.client IS NULL OR LENGTH(TRIM(NEW.client)) = 0 THEN
    SELECT name INTO NEW.client
    FROM clients
    WHERE id = NEW.client_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_invoices_fill_client
BEFORE INSERT OR UPDATE ON invoices
FOR EACH ROW EXECUTE FUNCTION fill_invoice_client();

-- ===============================
-- FUNCTIONS
-- ===============================

-- Get invoice items
CREATE OR REPLACE FUNCTION public.getInvoiceItems(p_invoice_id INT)
RETURNS TABLE(
    id INT,
    product TEXT,
    qte INT,
    price NUMERIC(12,2),
    total NUMERIC(12,2),
    observation TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        i.id,
        COALESCE(i.product, p.name) AS product,
        i.qte,
        i.price,
        i.total,
        i.observation
    FROM invoice_items i
    LEFT JOIN products p ON p.id = i.product_id
    WHERE i.invoice_id = p_invoice_id;
END;
$$ LANGUAGE plpgsql
SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.getInvoiceItems(INT) TO public;

-- Get invoices
CREATE OR REPLACE FUNCTION public.getInvoices()
RETURNS TABLE(
    id INT,
    ref CHAR(15),
    client_id INT,
    total NUMERIC(12,2),
    status VARCHAR(50),
    client TEXT,
    observation TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        inv.id,
        inv.ref,
        inv.client_id,
        inv.total,
        inv.status,
        COALESCE(NULLIF(TRIM(inv.client), ''), c.name) AS client,
        inv.observation,
        inv.created_at,
        inv.updated_at
    FROM invoices inv
    LEFT JOIN clients c ON c.id = inv.client_id;
END;
$$ LANGUAGE plpgsql
SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.getInvoices() TO public;
